import type { SiteContent } from "@/lib/types";

export const defaultSiteContent: SiteContent = {
  brand: {
    name: "CodeSpire",
    logoUrl: "https://i.postimg.cc/YhzcMz8R/logo.png",
    logoAlt: "CodeSpire logo",
  },
  navigation: {
    items: [
      { path: "/", label: "Home" },
      { path: "/subjects", label: "Subjects" },
      { path: "/presentations", label: "Presentations" },
      { path: "/videos", label: "Videos" },
      { path: "/playground", label: "Playground" },
      { path: "/quiz", label: "Quiz" },
      { path: "/contact", label: "Contact" },
      { path: "/admin", label: "Admin" },
    ],
    searchPlaceholder: "Search subjects, notes, presentations, quizzes, contact info...",
  },
  footer: {
    description: "Your ultimate study companion for mastering programming.",
    copyright: "© 2026 CodeSpire. Built with passion for learning.",
    learnLinks: [
      { label: "Subjects", path: "/subjects" },
      { label: "Presentations", path: "/presentations" },
      { label: "Playground", path: "/playground" },
      { label: "Quizzes", path: "/quiz" },
    ],
    connectLinks: [
      { label: "Contact", path: "/contact" },
      { label: "Instagram", path: "https://instagram.com/codespire", external: true },
      { label: "GitHub", path: "https://github.com/codespire", external: true },
    ],
    resourceLinks: [
      { label: "Admin", path: "/admin" },
      { label: "Firebase JSON", path: "/admin" },
    ],
  },
  home: {
    badge: "Your Ultimate Study Companion",
    titlePrefix: "Learn. Code.",
    titleAccent: "Inspire.",
    description: "Master programming with structured notes, image-rich learning blocks, a fast built-in playground, separate presentations, and quizzes — all powered by Firebase content.",
    primaryCta: "Start Learning",
    secondaryCta: "Try Playground",
    codePreviewLabel: "playground.py",
    codePreviewCode: "# Welcome to CodeSpire Playground!\nfor i in range(5):\n    print(f'Hello {i}')",
    heroImage: "/content/study-hub.svg",
    stats: [
      { icon: "BookOpen", value: "50+", label: "Subjects" },
      { icon: "Target", value: "500+", label: "Topics" },
      { icon: "Layers", value: "1000+", label: "Notes" },
      { icon: "Brain", value: "200+", label: "Quizzes" },
    ],
    learningPathsTitle: "Popular",
    learningPathsAccent: "Learning Paths",
    learningPathsDescription: "Follow curated paths designed to take you from beginner to advanced.",
    learningPaths: [
      { title: "Python Mastery", topics: "45 topics covered", icon: "🐍", image: "/content/code-lab.svg" },
      { title: "C Programming", topics: "38 topics covered", icon: "⚡", image: "/content/study-hub.svg" },
      { title: "SQL & Databases", topics: "30 topics covered", icon: "🗄️", image: "/content/data-grid.svg" },
      { title: "Data Structures", topics: "52 topics covered", icon: "🏗️", image: "/content/connect-wave.svg" },
    ],
    featuresTitle: "Everything You Need to",
    featuresAccent: "Excel",
    featuresDescription: "Comprehensive tools designed to accelerate your learning journey.",
    features: [
      { icon: "BookOpen", title: "Structured Notes", description: "Organized subjects, units, topics, and detailed study notes.", image: "/content/data-grid.svg" },
      { icon: "Presentation", title: "Separate PPT Section", description: "Watch live presentations in their own section with embeds and thumbnails.", image: "/content/study-hub.svg" },
      { icon: "Code", title: "Built-in Playground", description: "Switch between Python, SQL, and C instantly with a built-in editor UI and AI execution.", image: "/content/code-lab.svg" },
      { icon: "Brain", title: "Interactive Quizzes", description: "Test your knowledge with subject-wise quizzes and instant explanations.", image: "/content/connect-wave.svg" },
      { icon: "Target", title: "Editable Content", description: "Every label, quote, contact item, and image URL can be changed from Firebase.", image: "/content/data-grid.svg" },
      { icon: "Users", title: "Realtime Updates", description: "Changes made in the admin panel sync across the website instantly.", image: "/content/connect-wave.svg" },
    ],
    whyTitle: "Why choose",
    whyAccent: "CodeSpire",
    whyDescription: "We believe learning to code should be accessible, visual, and fully customizable.",
    whyImage: "/content/study-hub.svg",
    whyPoints: [
      "All website text is controlled by Firebase JSON",
      "AI-powered code execution with instant editor switching",
      "Separate presentations section with live embeds",
      "Downloadable notes in TXT format",
      "Dark and light mode for comfortable studying",
      "Search across subjects, notes, presentations, quizzes, and contact info",
    ],
    testimonialsTitle: "What Our",
    testimonialsAccent: "Students Say",
    testimonialsDescription: "Join learners who love the visual and editable experience.",
    testimonials: [
      { name: "Priya S.", role: "CS Student", quote: "CodeSpire made learning DSA so much easier.", avatar: "PS", image: "/content/study-hub.svg" },
      { name: "Alex M.", role: "Developer", quote: "The built-in playground switches instantly now.", avatar: "AM", image: "/content/code-lab.svg" },
      { name: "Sarah K.", role: "Educator", quote: "I can update the entire website from Firebase without touching code.", avatar: "SK", image: "/content/connect-wave.svg" },
    ],
    ctaTitle: "Ready to Start Learning?",
    ctaDescription: "Dive into structured courses, practice coding, view presentations, and test your knowledge.",
    ctaPrimary: "Get Started",
    ctaSecondary: "Contact Us",
    ctaImage: "/content/code-lab.svg",
  },
  pages: {
    subjects: {
      badge: "Browse All Courses",
      title: "Subjects",
      description: "Choose a subject to dive deep into structured learning with notes, presentations, and quizzes.",
      heroImage: "/content/study-hub.svg",
      cardFallbackImage: "/content/data-grid.svg",
      error: "Failed to load subjects. Make sure Firebase data is uploaded.",
      emptyTitle: "No Subjects Yet",
      emptyDescription: "Upload the JSON data to your Firebase Realtime Database to see subjects here.",
      exploreLabel: "Explore Subject",
    },
    subjectDetail: {
      backLabel: "Back to Subjects",
      unitsTitle: "Units",
      empty: "No units available.",
      notFound: "Subject not found.",
    },
    unitDetail: {
      backLabel: "Back to Units",
      topicsTitle: "Topics",
      empty: "No topics available.",
      notesSuffix: "notes",
      viewNotesLabel: "View Notes",
      notFound: "Unit not found.",
    },
    topicDetail: {
      backLabel: "Back to Topics",
      notesTitle: "Notes",
      noNotes: "No text notes available.",
      selectTitle: "Select a note to view",
      selectDescription: "Choose a note from the sidebar to start reading.",
      downloadLabel: "Download TXT",
      presentationsNotice: "{count} presentation notes moved to the Presentations section",
      notFound: "Topic not found.",
    },
    presentations: {
      badge: "Visual Learning Library",
      title: "Presentations",
      description: "Browse live PPT embeds, thumbnails, and downloadable deck links in one separate section.",
      emptyTitle: "No Presentations Yet",
      emptyDescription: "Upload presentation JSON to Firebase to show decks here.",
      openLabel: "Open Presentation",
      viewerTitle: "Live Presentation Viewer",
      iframeTitle: "Presentation viewer",
      noEmbed: "Add an embedUrl or fileUrl in Firebase to show the live presentation here.",
      downloadFile: "Download Deck",
    },
    playground: {
      title: "Code Playground",
      description: "Write, run, and experiment with code in real-time.",
      localNotice: "The playground now uses a built-in editor surface with instant Python, C, and SQL switching and AI-powered execution.",
      runLabel: "Run",
      outputTitle: "Output",
      runningLabel: "Running...",
      runningOutput: "Executing your code...",
      emptyOutput: "Click Run to execute your code and see output here...",
      executionError: "Could not execute your code.",
      initializingMessage: "Preparing the workspace...",
      sideImage: "/content/code-lab.svg",
      examples: {
        python: {
          code: "# Python Playground 🐍\nprint('Hello, CodeSpire!')\n\nfor number in range(1, 6):\n    print(f'Square of {number} = {number ** 2}')",
          helper: "Python keywords highlight instantly and switch without reloading.",
          title: "Python Workspace",
        },
        c: {
          code: "// C Playground ⚡\n#include <stdio.h>\n\nint main() {\n    for (int i = 1; i <= 5; i++) {\n        printf(\"Step %d\\n\", i);\n    }\n    return 0;\n}",
          helper: "C starter code appears instantly with a compiler-style editor theme.",
          title: "C Compiler View",
        },
        sql: {
          code: "-- SQL Playground 🗄️\nSELECT 'CodeSpire' AS platform, 'Ready' AS status;\nSELECT 7 * 6 AS answer;",
          helper: "SQL examples load immediately and keep the editor visible on every tab.",
          title: "SQL Query Console",
        },
      },
    },
    quiz: {
      badge: "Test Your Knowledge",
      title: "Quizzes",
      description: "Challenge yourself with interactive quizzes and track your progress.",
      backLabel: "Back to quizzes",
      emptyTitle: "No Quizzes Yet",
      emptyDescription: "Upload quiz data to Firebase to see quizzes here.",
      scoreLabel: "Score",
      questionLabel: "Question",
      explanationLabel: "Explanation",
      retryLabel: "Retry Quiz",
      nextLabel: "Next Question",
      seeResultsLabel: "See Results",
      resultsPrefix: "You scored",
    },
    notFound: {
      title: "404",
      description: "Oops! Page not found",
      linkLabel: "Return to Home",
    },
    videoLectures: {
      badge: "Watch & Learn",
      title: "Video Lectures",
      description: "Watch tutorial videos and lectures to boost your understanding.",
      emptyTitle: "No Video Lectures Yet",
      emptyDescription: "Upload video lecture data to Firebase to see them here.",
      watchLabel: "Watch Now",
    },
  },
  contact: {
    badge: "We'd love to hear from you",
    titlePrefix: "Get in",
    titleAccent: "Touch",
    description: "Have a question, suggestion, or want to collaborate? Reach out and we'll get back to you as soon as possible.",
    heroImage: "/content/connect-wave.svg",
    infoCards: [
      { icon: "Mail", label: "Email", value: "hello@codespire.dev", href: "mailto:hello@codespire.dev", image: "/content/connect-wave.svg" },
      { icon: "Phone", label: "Phone", value: "+1 (555) 123-4567", href: "tel:+15551234567", image: "/content/study-hub.svg" },
      { icon: "MapPin", label: "Location", value: "San Francisco, CA", href: "#", image: "/content/data-grid.svg" },
      { icon: "Globe", label: "Website", value: "codespire.dev", href: "https://codespire.dev", image: "/content/code-lab.svg" },
    ],
    formTitlePrefix: "Send us a",
    formTitleAccent: "Message",
    formDescription: "Fill out the form and we'll get back to you within 24 hours.",
    fields: { name: "Your Name", email: "Email", subject: "Subject", message: "Message" },
    placeholders: {
      name: "John Doe",
      email: "john@example.com",
      subject: "What's this about?",
      message: "Tell us more...",
    },
    submitLabel: "Send Message",
    successTitle: "Message Sent!",
    successDescription: "Thank you for reaching out. We'll respond soon.",
    socialTitlePrefix: "Connect with",
    socialTitleAccent: "Us",
    socialDescription: "Follow us on social media for updates, tips, and community content.",
    socials: [
      { icon: "Instagram", label: "Instagram", href: "https://instagram.com/codespire", handle: "@codespire", image: "/content/connect-wave.svg" },
      { icon: "Twitter", label: "Twitter", href: "https://twitter.com/codespire", handle: "@codespire", image: "/content/code-lab.svg" },
      { icon: "Github", label: "GitHub", href: "https://github.com/codespire", handle: "codespire", image: "/content/data-grid.svg" },
      { icon: "Linkedin", label: "LinkedIn", href: "https://linkedin.com/company/codespire", handle: "CodeSpire", image: "/content/study-hub.svg" },
    ],
    faqTitle: "Frequently Asked Questions",
    faqDescription: "Find quick answers to common questions about CodeSpire.",
    faqs: [
      "Is CodeSpire free to use?",
      "How do I report a bug?",
      "Can I contribute content?",
    ],
    ctaTitlePrefix: "Let's Build Something",
    ctaTitleAccent: "Amazing",
    ctaTitleSuffix: "Together",
    ctaDescription: "Whether you're a student, educator, or developer — we're here to help.",
    ctaPrimary: "Email Us",
    ctaSecondary: "Follow Us",
    ctaImage: "/content/connect-wave.svg",
  },
  search: {
    buttonLabel: "Search...",
    emptyQuery: "Start typing to search across all website content",
    noResultsPrefix: "No results found for",
  },
};
